#!/bin/bash

echo "Small Test 01"
echo " $(cat test01name.txt) " | ./../gram2_test.native

echo " "
echo "Small Test 02"
echo " $(cat test02name.txt) " | ./../gram2_test.native

echo " "
echo "Small Test 03"
echo " $(cat test03name.txt) " | ./../gram2_test.native

echo " "
echo "Small Test 04"
echo " $(cat test04name.txt) " | ./../gram2_test.native

echo " "
echo "Small Test 05"
echo " $(cat test05name.txt) " | ./../gram2_test.native

echo " "
echo "Small Test 06"
echo " $(cat test06name.txt) " | ./../gram2_test.native

echo " "
echo "Small Test 07"
echo " $(cat test07name.txt) " | ./../gram2_test.native

echo " "
echo "Small Test 08"
#echo " $(cat test08name.txt) " | ./../gram2_test.native

echo " "
echo "Small Test 09"
#echo " $(cat test09name.txt) " | ./../gram2_test.native

echo " "
echo "Small Test 10"
#echo " $(cat test10name.txt) " | ./../gram2_test.native

echo " "
echo "Large Test 01"
#echo " $(cat largetest01name.txt) " | ./../gram2_test.native

echo " "
echo "Large Test 02"
#echo " $(cat largetest02name.txt) " | ./../gram2_test.native

echo " "
echo "Evaluation Tests"
echo " "
echo "Small Test 11"
echo " $(cat test11name.txt) " | ./../gram2_test.native
echo " Expected Value: 10"

echo " "
echo "Small Test 12"
echo " $(cat test12name.txt) " | ./../gram2_test.native
echo " Expected Values: 8, 6, 4, 4"

echo " "
echo "Small Test 13"
echo " $(cat test13name.txt) " | ./../gram2_test.native
echo "Not expected to work"

echo " "
echo "Small Test 14"
echo " $(cat test14name.txt) " | ./../gram2_test.native
echo "Not expected to work"

echo " "
echo "Small Test 15"
echo " $(cat test15name.txt) " | ./../gram2_test.native
echo "Not expected to work"

echo " "
echo "Small Test 16"
echo " $(cat test16name.txt) " | ./../gram2_test.native
echo "Not expected to work"

echo " "
echo "Small Test 17"
echo " $(cat test17name.txt) " | ./../gram2_test.native
echo "Not expected to work"

echo " "
echo "Small Test 18"
echo "Not Written"
echo " $(cat test18name.txt) " | ./../gram2_test.native
echo "Not expected to work"

echo " "
echo "Small Test 19"
echo "Not Written"
#echo " $(cat test19name.txt) " | ./../gram2_test.native

echo " "
echo "Small Test 20"
echo "Not Written"
#echo " $(cat test20name.txt) " | ./../gram2_test.native

echo " "
echo "Large Test 03"
echo " $(cat largetest03name.txt) " | ./../gram2_test.native
echo "Not expected to work"
