#!/bin/bash

echo "Small Test 01"
echo " $(cat test01.txt) " | ./gram2_test.native

echo " "
echo "Small Test 02"
echo " $(cat test02.txt) " | ./gram2_test.native

echo " "
echo "Small Test 03"
echo " $(cat test03.txt) " | ./gram2_test.native

echo " "
echo "Small Test 04"
echo " $(cat test04.txt) " | ./gram2_test.native

echo " "
echo "Small Test 05"
echo " $(cat test05.txt) " | ./gram2_test.native

echo " "
echo "Small Test 06"
echo " $(cat test06.txt) " | ./gram2_test.native

echo " "
echo "Small Test 07"
echo " $(cat test07.txt) " | ./gram2_test.native

echo " "
echo "Small Test 08"
echo " $(cat test08.txt) " | ./gram2_test.native

echo " "
echo "Small Test 09"
echo " $(cat test09.txt) " | ./gram2_test.native

echo " "
echo "Small Test 10"
echo " $(cat test10.txt) " | ./gram2_test.native

echo " "
echo "Large Test 01"
echo " $(cat test11.txt) " | ./gram2_test.native
